language: cpp
dist: trusty
sudo: required

compiler:
- gcc
- clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # Apparently c++11 <regex> not fully implemented till 4.9
    - gcc-5
    - g++-5
    - clang-3.6

script:
# Build htslib
- cd htslib && autoheader && autoconf && ./configure && make && cd ../
- mkdir build && cd build
# Tests in debug and release build tests
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug ..
- make && cd ../ && bin/vargas test
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..
- make && cd ../ && bin/vargas test

notifications:
  email: false
  slack:
    secure: tPC+16jA/yTWMvq4mx3eA1Is6/V4PPZbBcTmtvmzx6BIjFzGLobDomDLjGgCYHV4fEc1DpqywplWChwsZ9ndb4iGGGxMubmQduRCklDTfAluPfOQQIa7HgT425YGaYVEM1CP+8Q4HMlgOtpbHbeg4U8Djk0g0Z/QMXbREwGbbMEr95LfTwn5YivoGMObssbqJAlw+AaWYYWBYBAeL6WLNB/I1Yl8ur22fXBicjvVScjyy0R8RmriHceZRIAZtTFb92xGQyB8Ca320mNibSI1Hk+qb1VSg7TN1sHFNT15HIzYb/wsWN11VdPOXGqNPLFTzs2a+GBcLTMZuzSfVeQqinQwGfu65UoHCtNGMKiNy6k7yx+oPUchzj+fD12V5TbnfzPlKlcZXshnewsHsPYhwOCH0+R6pXIm17IJwdCcXpsoSckeXrUSQpe4WLesqT2Mztz6Pw4r+VToaXREgaZk2tMMn+W7SOl21YTDHjvkVrs5qBbSou5wPaNS3NObsYkSoqNUOgn+I3dgYwpwscgiXa15xiXxd4rFu42qYUQVt6zJ2lsTdpd/yXckvU2ARHlhez8hTQzkQ7B76RKIQnCKvIJT26LvLWtcoA+y+QnorWiAQHUwPmJUjgSFVLkrDWjjMiBDkwOhiskjLBlVVBppvxUUVBwXXaQjthfaz1kTVhY=

# whitelist
branches:
  only:
    - master
